name: test matrix
on:
  push:
    branches:
      - master
  pull_request:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: [self-hosted,linux]
    if: github.ref != 'refs/heads/master'
    steps:
     - uses: actions/checkout@v2.3.1
     - name: Cancel Previous Runs
       uses: styfle/cancel-workflow-action@0.9.1
       with:
         access_token: ${{ github.token }}
     - name: Dependency install
       run: nix-build -A pkgs.yarn default.nix && nix-env -i ./result
     - name: Miso build
       run: nix-build
     - name: Diffing tests
       run: cd tests && yarn && yarn test

  deploy:
    runs-on: [self-hosted,linux]
    if: github.ref == 'refs/heads/master'
    steps:
     - uses: actions/checkout@v2.3.1
     - name: Dependency install
       run: nix-build -A pkgs.yarn default.nix && nix-env -i ./result
     - name: Miso build
       run: nix-build
     - name: Deploy
       run: nix-build -A deploy && ./result
       env:
         AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
         AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
         DEPLOY: '${{ secrets.DEPLOY }}'
         EMAIL: '${{ secrets.EMAIL }}'
